export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const LOAD_ERROR = 'LOAD_ERROR';
export const LOAD_SUCCESS = 'LOAD_SUCCESS';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const SET_ELECTION = 'SET_ELECTION';
export const ELECTION_ERROR = 'ELECTION_ERROR';
export const SET_CURR = 'SET_CURR';
export const VOTE_CURR = 'VOTE_CURR';
export const SET_LOADING = 'SET_LOADING';


